### ISSUE TITLE
sourceDir deprecated

### ISSUE THREAD

**Issue by wefixit-AT** [houbie/lesscss-gradle-plugin#4]
It seems sourceDir is deprecated for the example described in the readme:

> lessc {
>     sourceDir "customized/less", "standard/less"
>     include "**/*.less", "**/*.js"
>     exclude "imports/**/*"
>     destinationDir = "$buildDir/css"
> }

Thats the gradle output:
```
The TaskInputs.sourceDir(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.dir(Object).skipWhenEmpty() instead.
        at build_b3oaeftky8o30gysocdm19zch$_run_closure7.doCall(<path removed>/build.gradle:105)
```

**Comment by houbie** [comment]
See the deprecation warning in the readme
